# Generated by Django 3.2.4 on 2021-08-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='orders',
            name='address2',
            field=models.CharField(default='', max_length=300),
        ),
    ]
